/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_casino;

/**
 *
 * @author david
 */
public class Interfaz extends javax.swing.JFrame {
    Dado dadoInterfaz;
    Dado dadoInterfaz2;
    Jugador pepitoInterfaz;
    
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        etiquetaDado1 = new javax.swing.JTextField();
        etiquetaDado2 = new javax.swing.JTextField();
        botonLanzar = new javax.swing.JButton();
        etiquetaResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiquetaApuesta = new javax.swing.JTextField();
        etiquetaBilletera = new javax.swing.JTextField();
        etiquetaMensaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetaDado2ActionPerformed(evt);
            }
        });

        botonLanzar.setText("Lanzar");
        botonLanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLanzarMouseClicked(evt);
            }
        });
        botonLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLanzarActionPerformed(evt);
            }
        });

        jLabel1.setText("Apuesta:");

        jLabel2.setText("Billetera: ");

        jLabel3.setText("Mensaje: ");

        etiquetaApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetaApuestaActionPerformed(evt);
            }
        });

        etiquetaMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetaMensajeActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(etiquetaDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(etiquetaDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiquetaMensaje))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonLanzar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(etiquetaBilletera, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(etiquetaApuesta)))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonLanzar)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiquetaApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiquetaBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiquetaDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetaDado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaDado2ActionPerformed

    private void etiquetaApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetaApuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaApuestaActionPerformed

    private void etiquetaMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetaMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaMensajeActionPerformed

     
    private void botonLanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLanzarMouseClicked
        this.dadoInterfaz.lanzar();
        this.dadoInterfaz2.lanzar();
        
        int valor1=this.dadoInterfaz.valor;
        int valor2=this.dadoInterfaz2.valor;
        int resultadodados=valor1+valor2;        
        
        String cadena1= Integer.toString(valor1);
        etiquetaDado1.setText(cadena1);
        String cadena2= Integer.toString(valor2);
        etiquetaDado2.setText(cadena2);
        String cadena3=Integer.toString(resultadodados);
        etiquetaResultado.setText(cadena3); 
        if(resultadodados==2){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dados2()));
          etiquetaMensaje.setText("Pierdes la apuesta");
        }
        if(resultadodados==3){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dados3()));
          etiquetaMensaje.setText("Pierdes el doble de la apuesta");
        }
        if(resultadodados==7){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dados7()));
          etiquetaMensaje.setText("Ganas el doble de la apuesta");
        }
        if(resultadodados==11){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dados11()));
          etiquetaMensaje.setText("No pierdes nada");
        }
        if(resultadodados==12){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dados12()));
          etiquetaMensaje.setText("Ganas la apuesta");
        }
        //1,4,5,6,8,9,10
        if(resultadodados==1){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==4){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==5){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==6){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==8){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==9){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        if(resultadodados==10){
            pepitoInterfaz.Billetera=Double.parseDouble(etiquetaBilletera.getText());
          pepitoInterfaz.Apuesta=Double.parseDouble(etiquetaApuesta.getText());
          etiquetaBilletera.setText(String.valueOf(pepitoInterfaz.resultado_dadosotros()));
          etiquetaMensaje.setText("Pierdes el 3/2 de la apuesta");
        }
        //this.etiquetaDado1.setText(Integer.toString(this.dadoInterfaz.valor));
        //this.etiquetaDado2.setText(Integer.toString(this.dadoInterfaz2.valor));
    }//GEN-LAST:event_botonLanzarMouseClicked

    private void botonLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLanzarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLanzar;
    private javax.swing.JTextField etiquetaApuesta;
    private javax.swing.JTextField etiquetaBilletera;
    private javax.swing.JTextField etiquetaDado1;
    private javax.swing.JTextField etiquetaDado2;
    private javax.swing.JTextField etiquetaMensaje;
    private javax.swing.JTextField etiquetaResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
